feature_name：game_name_category
    JJ斗地主：0
    JJ象棋：1
    JJ麻将：2
    NBA篮球大师：3
    一念逍遥：4
    万宁象棋双人联机：5
    三国吧兄弟：6
    三国如龙传：7
    三国志战略版：8
    三国杀：9
    不良人3：10
    世界之外：11
    九州仙剑传：12
    九州异兽记：13
    伏魔者2：14
    众矢之地：15
    使命先锋：16
    侍忍者：17
    保卫萝卜4：18
    元梦之星：19
    元气骑士前传：20
    光·遇：21
    光明勇士：22
    全明星街球派对：23
    全民找一找：24
    全民找茬：25
    全民枪神：边境王者：26
    八牛斗地主：27
    决战圣殿：28
    决战地牢：29
    决战！平安京：30
    决胜巅峰：31
    动物历险记：32
    勇士与冒险：33
    北凉悍刀行：34
    危境：35
    原始征途：36
    友旗麻将：37
    古魂：38
    召唤神龙万宁版：39
    台球帝国：40
    台球游戏大师：41
    哈利波特：魔法觉醒：42
    嘻嘻红中麻将：43
    国王指意：44
    地下城与王国：45
    地铁跑酷：46
    坦克世界闪击战：47
    多乐升级：48
    多乐够级：49
    大话西游：归来：50
    天使之战：51
    天天台球：52
    天龙八部荣耀版：53
    太空杀：54
    失落城堡：55
    奇葩战斗家：56
    奥比岛：梦想国度：57
    奥特曼传奇英雄：58
    实况足球：59
    宫爆：老奶奶家族篇：60
    家园卫士：61
    富豪麻将：62
    小冰冰传奇：63
    少年仙界传：64
    尘白禁区：65
    山海经幻想录：66
    山海经异兽录：67
    巅峰战舰：68
    巅峰极速：69
    巨像文明：70
    巨兽战场：71
    幻想仙灵：72
    开心消消乐：73
    开运麻将：74
    弹壳特攻队：75
    微乐四川麻将：76
    微乐斗地主：77
    恋与深空：78
    我和我的天宫：79
    我的世界：80
    我的坦克我的团：81
    我的安吉拉2：82
    我的汤姆猫2：83
    战双帕弥什：84
    战斗法则：85
    战火勋章：86
    战舰猎手：87
    拳魂觉醒：88
    指尖四川麻将：89
    掌机小精灵：90
    攻城掠地：91
    文明与征服：92
    新不良人：93
    无尽噩梦5怨灵咒：94
    无尽的拉格朗日：95
    无悔华夏：96
    无间梦境：97
    时空中的绘旅人手游：98
    明日之后：99
    明日方舟：100
    星球：重启：101
    晶核：102
    暗黑破坏神：不朽：103
    暴力飞车2.0：104
    曙光之城：105
    曙光英雄：106
    最佳球会：107
    最封神：108
    月圆之夜：109
    末日血战：110
    机甲战队：111
    极无双2：112
    格斗城之战：113
    桃花源记：114
    梦三国：115
    梦幻家园：116
    梦幻西游：117
    植物大战僵尸2：118
    欢乐战三国：119
    欢喜斗地主：120
    正中靶心：121
    永不言弃2：122
    汤姆猫跑酷：123
    混沌起源：124
    源战役：125
    滑雪大冒险：126
    滚动的天空：127
    火线出击：128
    烧脑大挑战：129
    热血江湖手游：130
    独奏骑士：131
    狼人对决：132
    狼人杀：133
    猎人协会：134
    猎人王：135
    王牌竞速：136
    球场风云：137
    球球大作战：138
    画狐：139
    疯狂动物园：140
    皮卡堂之梦想起源：141
    矩阵临界：失控边缘：142
    砰砰军团：143
    神州千食舫：144
    神雕侠侣2：145
    禅游斗地主：146
    秦皇汉武：147
    竞技麻将：148
    第五人格：149
    篮下王者：150
    篮球高高手：151
    纪念碑谷：152
    绝世仙王：153
    绯色回响：154
    航海王：燃烧意志：155
    芒果斗地主：156
    英魂之刃：157
    葫芦娃大作战：158
    蛋仔派对：159
    行侠仗义五千年：160
    街机三国：161
    装甲前线：162
    装甲联队online：163
    见习猎魔团：164
    识字大师：165
    诛天剑侠：166
    贪吃的苹果蛇：167
    贪吃蛇在线：168
    贪吃蛇大作战：169
    赖子斗地主：170
    超凡先锋：171
    超能世界：172
    轩辕剑龙舞云山：173
    这也能切：174
    远征2：175
    远征手游：176
    迷你世界：177
    逃跑吧！少年：178
    途游中国象棋：179
    途游斗地主（比赛版）：180
    途游麻将：181
    重返未来：1999：182
    铁杆三国：183
    铁甲风暴：184
    镇魔曲：185
    长安幻想：186
    闪耀暖暖：187
    问道：188
    闯关专家：189
    闲来斗地主：190
    青云传：191
    非人学园：192
    风暴之眼：193
    飞吧龙骑士：194
    魂之追梦：195
    魔域手游：196
    魔塔50层勇者的试炼：197
    魔塔传说：198
    魔法战线：199
    鱼吃鱼：200
    麻将传奇：201
    黑暗之潮：契约：202
    龙之战歌：203

feature_name：greatest_vv_game_tag_name_category
    ：0
    Apex英雄：1
    CS1.6：2
    CSGO：3
    DOTA1：4
    DOTA2：5
    FIFA：6
    JJ军棋：7
    JJ斗地主：8
    JJ象棋：9
    JJ麻将：10
    NBA2K：11
    NBA2K OL2：12
    QQ三国：13
    QQ炫舞：14
    QQ飞车手游：15
    QQ飞车端游：16
    UFC-4：17
    一念逍遥：18
    七日世界：19
    万国觉醒：20
    三国志·战略版：21
    三国杀：22
    三角洲行动：23
    世界之外：24
    乐鸿捕鱼：25
    云顶之弈：26
    人渣：27
    代号：鸢：28
    会说话的汤姆猫：29
    你画我猜：30
    使命召唤：31
    使命召唤手游：32
    侠盗猎车手：33
    侠盗猎车手5：34
    俄罗斯方块：35
    保卫萝卜4：36
    元梦之星：37
    元气骑士前传：38
    光与夜之恋：39
    光遇：40
    全明星街球派对：41
    全民找茬：42
    全民枪神：边境王者：43
    其它游戏-仙侠类：44
    其它游戏-传奇奇迹类：45
    其它游戏-其它主机类：46
    其它游戏-其它休闲类：47
    其它游戏-其它棋牌类：48
    其它游戏-微信小游戏：49
    其它游戏-抖音小游戏：50
    其它游戏-特效游戏：51
    冲呀！饼干人：王国：52
    决战！平安京：53
    决胜巅峰：54
    剑网3：55
    劲舞团：56
    勇士与冒险：57
    原始征途：58
    原神：59
    反恐精英OL：60
    口袋奇兵：61
    台球帝国：62
    后室：63
    和平精英：64
    咸鱼之王：65
    四国军棋：66
    地下城与勇士：67
    地下城与勇士手游：68
    地铁跑酷：69
    坦克世界：70
    坦克世界：闪电战：71
    塞尔达传说：王国之泪：72
    多乐升级：73
    多乐够级：74
    大话西游：75
    大话西游2：76
    天天台球：77
    天天象棋：78
    天龙八部端游：79
    太空杀：80
    奥比岛：梦想国度：81
    奥特曼传奇英雄：82
    妄想山海：83
    实况足球：84
    富豪麻将：85
    寻道大千：86
    射雕：87
    小冰冰传奇：88
    崩坏：星穹铁道：89
    巅峰极速：90
    幻兽帕鲁：91
    开心消消乐：92
    开运麻将：93
    异世界勇者：94
    弹壳特攻队：95
    微乐斗地主：96
    忍者必须死3：97
    怪物猎人：世界：98
    恋与深空：99
    恐怖奶奶：100
    恐龙岛：101
    恐龙快打：102
    我的世界：103
    战争雷霆：104
    战双帕弥什：105
    战地5：106
    战斗法则：107
    战术小队：108
    拳皇97：109
    指尖四川麻将：110
    斗罗大陆：魂师对决：111
    方舟：112
    无尽噩梦5怨灵咒：113
    无尽的拉格朗日：114
    无悔华夏：115
    无畏契约：116
    明日之后：117
    星球：重启：118
    星际争霸：119
    星际战甲：120
    晶核：121
    暗区突围：122
    曙光英雄：123
    最佳球会：124
    最强NBA：125
    月圆之夜：126
    木筏求生：127
    未定事件簿：128
    梦幻西游：129
    梦幻西游手游：130
    植物大战僵尸：131
    植物大战僵尸2：132
    樱花校园模拟器：133
    欢喜斗地主：134
    欧洲卡车模拟2：135
    永不言弃2：136
    永劫无间：137
    汤姆猫跑酷：138
    沙盒与副本：英勇之地：139
    泰拉瑞亚：140
    洛克王国：141
    海底大猎杀：142
    游戏王：决斗链接：143
    滑雪大冒险：144
    火影忍者手游：145
    炉石传说：146
    狂野飙车9：竞速传奇：147
    狼人杀：148
    率土之滨：149
    王牌竞速：150
    王者荣耀：151
    现代战舰：152
    球球大作战：153
    生死狙击2：154
    皇室战争：155
    盖瑞模组：156
    禅游斗地主：157
    穿越火线：158
    穿越火线：枪战王者：159
    竞技麻将：160
    第五人格：161
    红色警戒2：162
    绝地求生：163
    罗布乐思：164
    航海王热血航线：165
    芒果斗地主：166
    英雄杀：167
    英雄联盟：168
    英雄联盟手游：169
    荒野乱斗：170
    荒野大镖客2：171
    萤火突击：172
    蛋仔派对：173
    行侠仗义五千年：174
    街头霸王2：175
    街头霸王6：176
    街机三国：177
    诛天剑侠：178
    贪吃的苹果蛇：179
    贪吃蛇在线：180
    贪吃蛇大作战：181
    超凡先锋：182
    超能世界：183
    足球世界：184
    跑跑卡丁车：185
    跑跑卡丁车官方竞速版：186
    车祸模拟器：187
    迷你世界：188
    逃离塔科夫：189
    逃跑吧！少年：190
    逆战：191
    逆战手游：192
    逆水寒：193
    逆水寒手游：194
    途游斗地主：195
    部落冲突：196
    都市：天际线：197
    重返未来1999：198
    金铲铲之战：199
    闪耀暖暖：200
    问道：201
    阴阳师：202
    雀魂麻将：203
    飞吧！龙骑士：204
    饥荒：205
    香肠派对：206
    高能英雄：207
    魔兽世界：208
    魔兽争霸3：209
    鱼吃鱼：210
    鸣潮：211
    鹅鸭杀：212
    黎明杀机：213

feature_name：greatest_duration_game_tag_name_category
    ：0
    60秒：1
    Apex英雄：2
    CS1.6：3
    CSGO：4
    DOTA1：5
    DOTA2：6
    FIFA：7
    JJ军棋：8
    JJ斗地主：9
    JJ象棋：10
    JJ麻将：11
    MUGEN：12
    NBA2K：13
    NBA2K OL2：14
    QQ三国：15
    QQ炫舞：16
    QQ飞车手游：17
    QQ飞车端游：18
    UFC-4：19
    i wanna：20
    万国觉醒：21
    三国吧兄弟：22
    三国志11：23
    三国志·战略版：24
    三国战纪：25
    三国杀：26
    三国群英传：27
    世界之外：28
    云顶之弈：29
    人渣：30
    代号：鸢：31
    会说话的汤姆猫：32
    你画我猜：33
    使命召唤：34
    使命召唤手游：35
    侠盗猎车手：36
    侠盗猎车手5：37
    侠盗猎车手：罪恶都市：38
    俄罗斯方块：39
    元梦之星：40
    元气骑士前传：41
    光与夜之恋：42
    光遇：43
    全明星街球派对：44
    全民枪神：边境王者：45
    全面战争模拟器：46
    其它游戏-仙侠类：47
    其它游戏-传奇奇迹类：48
    其它游戏-其它主机类：49
    其它游戏-其它休闲类：50
    其它游戏-其它棋牌类：51
    其它游戏-微信小游戏：52
    其它游戏-抖音小游戏：53
    其它游戏-特效游戏：54
    冲呀！饼干人：王国：55
    决战地牢：56
    决胜巅峰：57
    刀剑Online：58
    剑网3：59
    劲舞团：60
    原神：61
    双人成行：62
    口袋奇兵：63
    台球帝国：64
    后室：65
    和平精英：66
    咸鱼之王：67
    四国军棋：68
    地下城与勇士：69
    地下城与勇士手游：70
    地铁跑酷：71
    坦克世界：72
    坦克世界：闪电战：73
    塔瑞斯世界：74
    塞尔达传说：王国之泪：75
    境·界 刀鸣：76
    多乐升级：77
    多乐够级：78
    大话西游：79
    大话西游2：80
    天天台球：81
    天天象棋：82
    天龙八部端游：83
    太空杀：84
    奥比岛：梦想国度：85
    奥特曼传奇英雄：86
    妄想山海：87
    实况足球：88
    富豪麻将：89
    寻道大千：90
    射雕：91
    小冰冰传奇：92
    崩坏：星穹铁道：93
    巅峰极速：94
    幻兽帕鲁：95
    开心消消乐：96
    开运麻将：97
    弹壳特攻队：98
    微乐四川麻将：99
    微乐斗地主：100
    忍者必须死3：101
    怪物猎人：世界：102
    恋与深空：103
    恐惧饥荒：104
    恐鬼症：105
    恐龙岛：106
    我的世界：107
    我的汤姆猫：108
    战双帕弥什：109
    战地5：110
    战斗法则：111
    战术小队：112
    战火勋章：113
    战舰世界：114
    拳皇14：115
    拳皇97：116
    拳皇98：117
    指尖四川麻将：118
    摩尔庄园：119
    攻城掠地：120
    文字游戏：121
    斗罗大陆：魂师对决：122
    方舟：123
    旋转轮胎：124
    无尽噩梦5怨灵咒：125
    无尽的拉格朗日：126
    无畏契约：127
    明日之后：128
    明日方舟：129
    明日方舟：终末地：130
    星球：重启：131
    星际争霸：132
    晶核：133
    暗区突围：134
    暴爽疯狂赛车：135
    曙光英雄：136
    最佳球会：137
    最强NBA：138
    月圆之夜：139
    未定事件簿：140
    机甲战队：141
    极限国度：142
    极限竞速：地平线4：143
    极限竞速：地平线5：144
    梦三国：145
    梦三国端游：146
    梦幻西游：147
    梦幻西游手游：148
    植物大战僵尸：149
    植物大战僵尸2：150
    樱花校园模拟器：151
    欢乐斗地主：152
    欢喜斗地主：153
    欧洲卡车模拟2：154
    永劫无间：155
    汤姆猫跑酷：156
    沙盒与副本：英勇之地：157
    泰拉瑞亚：158
    洛克王国：159
    海底大猎杀：160
    游戏王：决斗链接：161
    滑雪大冒险：162
    火影忍者手游：163
    炉石传说：164
    狂野飙车9：竞速传奇：165
    狼人杀：166
    猫和老鼠：167
    率土之滨：168
    王牌竞速：169
    王者荣耀：170
    现代战舰：171
    球球大作战：172
    生化危机8：村庄：173
    生死狙击2：174
    白荆回廊：175
    皇室战争：176
    盖瑞模组：177
    石器时代：觉醒：178
    禅游斗地主：179
    穿越火线：180
    穿越火线：枪战王者：181
    第五人格：182
    红色警戒2：183
    绝地求生：184
    绯色回响：185
    罗布乐思：186
    群雄逐鹿：187
    航海王热血航线：188
    艾尔登法环：189
    芒果斗地主：190
    英雄杀：191
    英雄联盟：192
    英雄联盟手游：193
    荒野乱斗：194
    荒野大镖客2：195
    荣耀全明星：196
    萤火突击：197
    蛋仔派对：198
    行侠仗义五千年：199
    街头霸王2：200
    街头霸王6：201
    街机三国：202
    贪吃的苹果蛇：203
    贪吃蛇在线：204
    贪吃蛇大作战：205
    赛尔号：206
    超凡先锋：207
    超级马里奥派对：208
    超能世界：209
    足球世界：210
    跑跑卡丁车：211
    跑跑卡丁车官方竞速版：212
    车祸模拟器：213
    迷你世界：214
    迷你枪战精英：215
    逃离塔科夫：216
    逃跑吧！少年：217
    逆战：218
    逆水寒：219
    逆水寒手游：220
    途游斗地主：221
    部落冲突：222
    都市：天际线：223
    重返未来1999：224
    金铲铲之战：225
    长安幻想：226
    闪耀暖暖：227
    问道：228
    阴阳师：229
    雀魂麻将：230
    飞越13号房：231
    饥荒：232
    香肠派对：233
    骑马与砍杀2：霸主：234
    高能英雄：235
    魔兽世界：236
    魔兽争霸3：237
    鱼吃鱼：238
    鹅鸭杀：239
    黎明杀机：240
    黑神话：悟空：241

feature_name：greatest_like_game_tag_name_category
    ：0
    Apex英雄：1
    CSGO：2
    DOTA1：3
    DOTA2：4
    JJ斗地主：5
    JJ象棋：6
    NBA2K：7
    NBA2K OL2：8
    QQ飞车手游：9
    三国志·战略版：10
    三国杀：11
    世界之外：12
    云顶之弈：13
    代号：鸢：14
    使命召唤手游：15
    侠盗猎车手5：16
    元梦之星：17
    元气骑士前传：18
    光与夜之恋：19
    光遇：20
    全明星街球派对：21
    全民枪神：边境王者：22
    其它游戏-其它主机类：23
    其它游戏-其它休闲类：24
    其它游戏-微信小游戏：25
    其它游戏-抖音小游戏：26
    其它游戏-特效游戏：27
    冲呀！饼干人：王国：28
    剑网3：29
    原神：30
    口袋奇兵：31
    和平精英：32
    地下城与勇士：33
    地铁跑酷：34
    塞尔达传说：王国之泪：35
    太空杀：36
    妄想山海：37
    实况足球：38
    富豪麻将：39
    小冰冰传奇：40
    崩坏：星穹铁道：41
    巅峰极速：42
    幻兽帕鲁：43
    弹壳特攻队：44
    微乐斗地主：45
    恋与深空：46
    恐龙岛：47
    我的世界：48
    战地5：49
    战术小队：50
    拳皇97：51
    指尖四川麻将：52
    无畏契约：53
    明日之后：54
    星球：重启：55
    晶核：56
    暗区突围：57
    曙光英雄：58
    未定事件簿：59
    梦幻西游：60
    梦幻西游手游：61
    植物大战僵尸：62
    植物大战僵尸2：63
    樱花校园模拟器：64
    欧洲卡车模拟2：65
    永劫无间：66
    火影忍者手游：67
    狼人杀：68
    王者荣耀：69
    现代战舰：70
    穿越火线：71
    穿越火线：枪战王者：72
    第五人格：73
    红色警戒2：74
    绝地求生：75
    艾尔登法环：76
    英雄联盟：77
    英雄联盟手游：78
    荒野乱斗：79
    蛋仔派对：80
    行侠仗义五千年：81
    街头霸王2：82
    贪吃蛇大作战：83
    足球世界：84
    迷你世界：85
    逃离塔科夫：86
    逆水寒：87
    逆水寒手游：88
    途游斗地主：89
    重返未来1999：90
    金铲铲之战：91
    阴阳师：92
    饥荒：93
    魔兽世界：94
    魔兽争霸3：95
    鱼吃鱼：96
    鸣潮：97

