date: unused
user_id: index
game_name: unused
is_treatment: treatment
is_login: label
exp_group: exp
game_vv: unused
game_consume_duration: unused
game_video_vv: unused
game_video_consume_duration: unused
game_live_watch_pv: unused
game_live_watch_duration: unused
finish_vv_daily: unused
valid_3s_vv_cnt_daily: unused
valid_vv_cnt_daily: unused
like_cnt_daily: unused
comment_cnt_daily: unused
follow_cnt_daily: unused
favourite_video_cnt_daily: unused
live_show_cnt_1d_daily: unused
live_watch_cnt_1d_daily: unused
live_single_10s_valid_watch_cnt_1d_daily: unused
live_single_30s_valid_watch_cnt_1d_daily: unused
live_single_3min_valid_watch_cnt_1d_daily: unused
live_comment_cnt_1d_daily: unused
live_send_gift_cnt_1d_daily: unused
live_follow_cnt_1d_daily: unused
live_share_cnt_1d_daily: unused
live_like_cnt_1d_daily: unused
latest_active_windows: used
recent_30d_active_cnt: used
launch_duration_mins_30d: used
gamevideo_consume_level_30d: used
gamelive_consume_level_30d: used
watch_layer: used
allvideo_min_now_last_video_show_days: used
allvideo_recent_1_month_total_video_show_days: used
allvideo_total_vv: used
allvideo_total_finish_vv: used
allvideo_total_play_time: used
gamevideo_min_now_last_video_show_days: used
gamevideo_recent_1_month_total_video_show_days: used
gamevideo_total_vv: used
gamevideo_total_finish_vv: used
gamevideo_total_play_time: used
alllive_min_now_last_show_days: used
alllive_min_now_last_watch_days: used
alllive_recent_1_month_total_show_days: used
alllive_recent_1_month_total_watch_days: used
alllive_total_show_pv: used
alllive_total_watch_pv: used
alllive_total_watch_duration: used
gamelive_min_now_last_show_days: used
gamelive_min_now_last_watch_days: used
gamelive_recent_1_month_total_show_days: used
gamelive_recent_1_month_total_watch_days: used
gamelive_total_show_pv: used
gamelive_total_watch_pv: used
gamelive_total_watch_duration: used