user_id: index
game_name: unused
is_treatment: treatment
is_login: label
exp_group: exp
video_vv_1d: unused
video_play_time_1d: unused
video_dislike_cnt_1d: unused
allvideo_min_now_last_video_show_days: used
allvideo_recent_1_month_total_video_show_days: used
allvideo_total_vv: used
allvideo_total_finish_vv: used
allvideo_total_play_time: used
gamevideo_min_now_last_video_show_days: used
gamevideo_recent_1_month_total_video_show_days: used
gamevideo_total_vv: used
gamevideo_total_finish_vv: used
gamevideo_total_play_time: used
alllive_min_now_last_show_days: used
alllive_min_now_last_watch_days: used
alllive_recent_1_month_total_show_days: used
alllive_recent_1_month_total_watch_days: used
alllive_total_show_pv: used
alllive_total_watch_pv: used
alllive_total_watch_duration: used
gamelive_min_now_last_show_days: used
gamelive_min_now_last_watch_days: used
gamelive_recent_1_month_total_show_days: used
gamelive_recent_1_month_total_watch_days: used
gamelive_total_show_pv: used
gamelive_total_watch_pv: used
gamelive_total_watch_duration: used
app_active_days: used
app_average_active_time_minute: used
app_active_time: used
category_age_range: used
category_city_level_resident: used
category_phone_market_price: used