user_id: index
game_name_category: unused
game_data_source: unused
is_video_treatment: treatment
is_liveshow_treatment: unused
is_livewatch_treatment: unused
video_vv_1d: unused
video_play_time_1d: unused
live_show_vv_1d: unused
live_watch_vv_1d: unused
live_watch_duration_1d: unused
login_success_cnt_1d: label
vid: exp
latest_active_windows: deep
recent_30d_active_cnt: deep
min_now_last_show_days: deep
min_now_last_watch_days: deep
recent_1_month_total_show_days: deep
recent_1_month_total_watch_days: deep
total_show_pv: deep
total_watch_pv: deep
total_10s_valid_watch_pv: deep
total_30s_valid_watch_pv: deep
total_3mins_valid_watch_pv: deep
total_watch_duration: deep
total_comment_pv: deep
total_send_amount: deep
total_follow_pv: deep
total_like_pv: deep
total_share_pv: deep
total_dislike_pv: deep
total_report_pv: deep
total_icon_click_pv: deep
total_download_pv: deep
total_install_pv: deep
average_show_pv: deep
average_watch_pv: deep
average_10s_valid_watch_pv: deep
average_30s_valid_watch_pv: deep
average_3mins_valid_watc_pv: deep
average_watch_duration: deep
average_comment_pv: deep
average_send_amount: deep
average_follow_pv: deep
average_like_pv: deep
average_share_pv: deep
average_dislike_pv: deep
average_report_pv: deep
average_click_pv: deep
average_download_pv: deep
average_install_pv: deep
min_now_last_video_show_days: deep
recent_1_month_total_video_show_days: deep
total_vv: deep
total_finish_vv: deep
total_valid_vv_cnt: deep
total_play_time: deep
total_like_cnt: deep
total_comment_cnt: deep
total_follow_cnt: deep
total_video_download_cnt: deep
total_share_video_cnt: deep
total_favourite_video_cnt: deep
total_repost_cnt: deep
total_dislike_cnt: deep
total_click_cnt: deep
total_download_cnt: deep
total_install_cnt: deep
average_vv: deep
average_finish_vv: deep
average_valid_vv: deep
average_play_time: deep
average_like_cnt: deep
average_comment_cnt: deep
average_follow_cnt: deep
average_video_download_cnt: deep
average_share_cnt: deep
average_favourite_cnt: deep
average_repost_cnt: deep
average_dislike_cnt: deep
average_click_cnt: deep
average_download_cnt: deep
average_install_cnt: deep
greatest_vv_game_tag_name_category: unused
greatest_duration_game_tag_name_category: unused
greatest_like_game_tag_name_category: unused
date: unused