author_id: index
is_publish: label
fans_num_all: unused
game_video_dau: unused
latest_days: unused
total_watch_item_cnt: unused
total_vv: unused
total_play_time: unused
game_cnt: unused
latest_7_total_watch_item_cnt: unused
latest_7_total_vv: unused
latest_7_total_play_time: unused
latest_7_total_game_cnt: unused
game_video_publish_cnt: unused
latest_publish_days: deep
total_publish_item_cnt: unused
total_publish_like_cnt: unused
total_fans_num: unused
latest_15_total_publish_item_cnt: unused
latest_15_total_publish_vv: unused
latest_15_total_publish_like_cnt: unused
latest_15_total_fans_num: unused
latest_30_total_publish_item_cnt: unused
latest_30_total_publish_vv: unused
latest_30_total_publish_like_cnt: unused
latest_30_total_fans_num: unused
live_watch_days: unused
latest_live_days: unused
total_show_room_cnt: unused
total_watch_room_cnt: unused
watch_duration: unused
latest_open_live_days: unused
open_live_days: unused
open_live_duration_1d: unused
open_watch_duration_1d: unused
open_follow_cnt_1d: unused
open_comment_cnt_1d: unused
latest_15_publish_vv_decay: unused
latest_15_publish_like_cnt_decay: unused
latest_15_publish_fans_num_decay: unused