author_id: index
table_status: unused
is_sab_stable_valid: unused
retention_status: label
is_promote: deep
is_aa_promote: deep
gender_category: deep
age_category: deep
fans_num_all: deep
anchor_type: deep
live_game_days: deep
acu: deep
live_minute_cnt_1d: deep
game_live_show_cnt_1d: unused
game_live_show_ucnt_1d: unused
game_watch_cnt_1d: deep
game_watch_ucnt_1d: deep
game_live_comment_cnt_1d: deep
game_live_comment_ucnt_1d: deep
game_live_share_cnt_1d: deep
game_live_share_ucnt_1d: deep
game_live_send_barrage_cnt_1d: unused
game_live_send_barrage_ucnt_1d: unused
game_live_dislike_cnt_1d: unused
game_live_dislike_ucnt_1d: unused
game_live_report_cnt_1d: unused
game_live_report_ucnt_1d: unused
game_new_follow_fans_ucnt_1d: deep
game_unfollow_anchor_ucnt_1d: deep
live_real_online_watch_ucnt_1mi: deep
live_fake_online_watch_ucnt_1mi: deep
live_popular_online_watch_ucnt_1mi: deep
live_total_online_watch_ucnt_1mi: deep